### ISSUE TITLE
Models not saved during training

### ISSUE THREAD

**Issue by ntyoshi** [mpariente/asteroid#162]
**Question**
I tried [asteroid/egs/wham/DPRNN/run.sh](https://github.com/mpariente/asteroid/blob/master/egs/wham/DPRNN/run.sh) but the error was occurred at the end of the training process.
The messages are below:

```
~~~
sep_clean_8kmin_7101f1a8/checkpoints/_ckpt_epoch_4.ckpt as top 5
Epoch 5: 100%|██████████| 4022/4022 [28:05<00:00,  2.39it/s, loss=-11.728, v_num=0, val_loss=-11.5]
Traceback (most recent call last):
  File "train.py", line 121, in <module>
    main(arg_dic)
  File "train.py", line 92, in main
    best_path = [b for b, v in best_k.items() if v == min(best_k.values())][0]
IndexError: list index out of range
~~~
```

I have tried to add some codes at [train.py](https://github.com/mpariente/asteroid/blob/master/egs/wham/DPRNN/train.py) and confirmed the length of checkpoint.best_k_models.items() is zero. 
And best_k_models.json contains only {}.

Does anyone have any idea to fix it?
Let me know if you have any comments.

**Environment**
- Python 3.7.7
- torch 1.5.1
- pytorch-lightning       0.7.6

- Ubuntu 18.04 on GCP

**Comment by mpariente** [comment]
Yes, I've had this before and it's a bug in pytorch-lightning model checkpoint that has been fixed in the new versions of it. 
We'll have to upgrade, if you want to write a patch, feel free. Otherwise, I'll probably get to it next week.

**Comment by ntyoshi** [comment]
@mpariente 
OK. I'll wait for you.
Could you tell me when you finish writing a patch?

**Comment by ntyoshi** [comment]
@mpariente 
I fixed the issue and created a pull request #184 .
If there isn't any problem, please close this issue.

**Comment by mpariente** [comment]
Let's keep this open until it's merged, thanks!
