### ISSUE TITLE
run train.py meets ValueError: `Dataloader` returned 0 length.

### ISSUE THREAD

**Issue by elenzheng** [mpariente/asteroid#270]
Hello!

I am studying the recipe of /asteroid-master/egs/dns_challenge/ and trying to run it for practice.
But I met error and I failed to train the model.
I run it in my laptop in Linux, I installed pytorch_lightning version 0.9.0 from PyPI.
But when I run /asteroid-master/egs/dns_challenge/baseline/run.sh at Stage 3 : Train, it will throw error at pytorch_lightning.
The error is as shown below. 
[Train_error_log.txt](https://github.com/mpariente/asteroid/files/5334160/Train_error_log.txt)
For more detail please find the attached Train_error_log.txt.
*************************************************************************************************
Traceback (most recent call last):
  File "train.py", line 121, in <module>
    main(arg_dic)
  File "train.py", line 94, in main
    trainer.fit(system)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.1rc4-py3.8.egg/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.1rc4-py3.8.egg/pytorch_lightning/trainer/trainer.py", line 1084, in fit
    results = self.accelerator_backend.train(model)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.1rc4-py3.8.egg/pytorch_lightning/accelerators/cpu_backend.py", line 39, in train
    results = self.trainer.run_pretrain_routine(model)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.1rc4-py3.8.egg/pytorch_lightning/trainer/trainer.py", line 1224, in run_pretrain_routine
    self._run_sanity_check(ref_model, model)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.1rc4-py3.8.egg/pytorch_lightning/trainer/trainer.py", line 1249, in _run_sanity_check
    self.reset_val_dataloader(ref_model)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.1rc4-py3.8.egg/pytorch_lightning/trainer/data_loading.py", line 337, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.1rc4-py3.8.egg/pytorch_lightning/trainer/data_loading.py", line 299, in _reset_eval_dataloader
    num_batches = len(dataloader) if _has_len(dataloader) else float('inf')
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.1rc4-py3.8.egg/pytorch_lightning/trainer/data_loading.py", line 70, in _has_len
    raise ValueError('`Dataloader` returned 0 length.'
ValueError: `Dataloader` returned 0 length. Please make sure that your Dataloader at least returns 1 batch
*************************************************************************************************
I have successfully run it for Stage 1 and 2, and the file_infos.json already created at location ./data.
I don't know what cause this `Dataloader` to return 0 length.
Can you help me to point out what maybe the cause?
How can I solve this problem?
Thanks in advance!

Best Regards,
Elen

**Comment by mpariente** [comment]
Can you attest the data is present on your disk?

**Comment by elenzheng** [comment]
![p1](https://user-images.githubusercontent.com/71864227/95216151-51d9b880-0824-11eb-8aa3-5e975249850d.png)
![p2](https://user-images.githubusercontent.com/71864227/95216166-57cf9980-0824-11eb-8170-cfbe757401fc.png)
![p3](https://user-images.githubusercontent.com/71864227/95216172-5900c680-0824-11eb-87f5-5a74f9cfc2dc.png)
[file_infos.json.txt](https://github.com/mpariente/asteroid/files/5334564/file_infos.json.txt)

Hi Mpariente,

I did not download all the datasets wav files from https://github.com/microsoft/DNS-Challenge.
I only downloaded a few wav files from that github.
Please find the screenshot I attached that you can know what data is present on my disk.
I also attached my file_infos.json file.
Please check if I missed something?

Thanks,
Elen

**Comment by elenzheng** [comment]
Hi Mpariente,

The default batch_size from the original conf.yml is 64. I did not change it.
Can you tell me why my batch size cannot be larger than 3?

Thanks,
Elen

**Comment by elenzheng** [comment]
Hi Mpariente,

I try to change the batch_size in the /local/conf.yml from 64 to 2. Then when I run Stage 3 I got below error:
**************************************************************************************
'elen printing: batch_size=2, num_workers=32'
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "train.py", line 123, in <module>
    main(arg_dic)
  File "train.py", line 96, in main
    trainer.fit(system)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.0-py3.8.egg/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.0-py3.8.egg/pytorch_lightning/trainer/trainer.py", line 1084, in fit
    results = self.accelerator_backend.train(model)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.0-py3.8.egg/pytorch_lightning/accelerators/cpu_backend.py", line 39, in train
    results = self.trainer.run_pretrain_routine(model)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.0-py3.8.egg/pytorch_lightning/trainer/trainer.py", line 1224, in run_pretrain_routine
    self._run_sanity_check(ref_model, model)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.0-py3.8.egg/pytorch_lightning/trainer/trainer.py", line 1257, in _run_sanity_check
    eval_results = self._evaluate(model, self.val_dataloaders, max_batches, False)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.0-py3.8.egg/pytorch_lightning/trainer/evaluation_loop.py", line 333, in _evaluate
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
  File "/home/elen/anaconda3/lib/python3.8/site-packages/pytorch_lightning-0.9.0-py3.8.egg/pytorch_lightning/trainer/evaluation_loop.py", line 687, in evaluation_forward
    output = model.validation_step(*args)
  File "/home/elen/lstm_rnn/asteroid-master/asteroid/engine/system.py", line 139, in validation_step
    loss = self.common_step(batch, batch_nb, train=False)
TypeError: common_step() got an unexpected keyword argument 'train'
(base) root@elen-VirtualBox:/home/elen/lstm_rnn/asteroid-master/egs/dns_challenge/baseline# 
***************************************************************************************

Can you kindly check again what maybe the cause?
Thanks a lot.

**Comment by mpariente** [comment]
- Because you don't have many examples. 
- What is your asteroid version? 

Please, try debugging before posting the issue, if you solve your problems, you'll be better after it.

**Comment by elenzheng** [comment]
I downloaded the default master Branch code just last week.
From the Changelog I found its version is [0.3.3] - 2020-08-25.
Now after removing the argument 'train' from common_step() in the code of /asteroid/engine/system.py,  I can successfully run the Stage 3 to train the model.
