### ISSUE TITLE
seems like something incompatible after torchaudio 0.7.0

### ISSUE THREAD

**Issue by SouppuoS** [mpariente/asteroid#289]
## 🐛 Bug

try to install asteroid on Colab, follow the installation steps in README

>ERROR: tensorflow 2.3.0 has requirement tensorboard<3,>=2.3.0, but you'll have tensorboard 2.2.0 which is incompatible.
ERROR: torchaudio 0.7.0 has requirement torch==1.7.0, but you'll have torch 1.6.0+cu101 which is incompatible.
ERROR: pytorch-lightning 0.9.0 has requirement future>=0.17.1, but you'll have future 0.16.0 which is incompatible.
ERROR: pytorch-lightning 0.9.0 has requirement PyYAML>=5.1, but you'll have pyyaml 3.13 which is incompatible.

and run a recipe
>Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from asteroid import DPRNNTasNet
  File "/content/asteroid/asteroid/__init__.py", line 3, in <module>
    from .models import ConvTasNet, DCCRNet, DCUNet, DPRNNTasNet, DPTNet, LSTMTasNet, DeMask
  File "/content/asteroid/asteroid/models/__init__.py", line 2, in <module>
    from .conv_tasnet import ConvTasNet
  File "/content/asteroid/asteroid/models/conv_tasnet.py", line 1, in <module>
    from ..filterbanks import make_enc_dec
  File "/content/asteroid/asteroid/filterbanks/__init__.py", line 6, in <module>
    from .griffin_lim import griffin_lim, misi
  File "/content/asteroid/asteroid/filterbanks/griffin_lim.py", line 7, in <module>
    from ..dsp.consistency import mixture_consistency
  File "/content/asteroid/asteroid/dsp/__init__.py", line 2, in <module>
    from .overlap_add import LambdaOverlapAdd, DualPathProcessing
  File "/content/asteroid/asteroid/dsp/overlap_add.py", line 3, in <module>
    from asteroid.losses.pit_wrapper import PITReorder
  File "/content/asteroid/asteroid/losses/__init__.py", line 8, in <module>
    from .stoi import NegSTOILoss as SingleSrcNegSTOI
  File "/content/asteroid/asteroid/losses/stoi.py", line 1, in <module>
    from torch_stoi import NegSTOILoss as _NegSTOILoss
  File "/usr/local/lib/python3.6/dist-packages/torch_stoi/__init__.py", line 1, in <module>
    from .stoi import NegSTOILoss
  File "/usr/local/lib/python3.6/dist-packages/torch_stoi/stoi.py", line 5, in <module>
    import torchaudio
  File "/usr/local/lib/python3.6/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from . import extension
  File "/usr/local/lib/python3.6/dist-packages/torchaudio/extension/__init__.py", line 5, in <module>
    _init_extension()
  File "/usr/local/lib/python3.6/dist-packages/torchaudio/extension/extension.py", line 12, in _init_extension
    _init_script_module(ext)
  File "/usr/local/lib/python3.6/dist-packages/torchaudio/extension/extension.py", line 19, in _init_script_module
    torch.classes.load_library(path)
  File "/usr/local/lib/python3.6/dist-packages/torch/_classes.py", line 46, in load_library
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.6/dist-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.6/dist-packages/torchaudio/_torchaudio.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_14DispatchKeySetE

find torchaudio [release a new version 0.7.0](https://pypi.org/project/torchaudio/#history) on Oct 28
fixed it by installing torchaudio 0.6.0 manually
maybe need version limitation on torchaudio in installation script.

**Comment by mpariente** [comment]
Let's pin torchaudio's version to 0.6.0 for now then. Do you mind submitting a PR?

**Comment by mpariente** [comment]
Just to be sure, how did you install torchaudio in the first place? Because it does work on my end..

**Comment by SouppuoS** [comment]
I found PyTorch have also relased a new version 1.7.0 on Oct 28...
It seems torchaudio 0.7.0 is based on torch 1.7.0, it will crash if you install a lower version like pytorch 1.6.0 (you can try it on colab which is installed 1.6.0 by default)
So, maybe both new version or both old version?

**Comment by mpariente** [comment]
Oh ok, I thought it didn't work with 1.7.0.. 
So we'll revert the PR I guess. 

Which colab are you talking about by the way?

**Comment by SouppuoS** [comment]
google colab
please revert it XD.
