### ISSUE TITLE
Unable to run evaluate step in dns challenge implementation

### ISSUE THREAD

**Issue by raikarsagar** [mpariente/asteroid#64]
Stage 5 : Evaluate
  0%|                                                                         | 0/150 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "eval_on_synthetic.py", line 194, in <module>
    main(arg_dic)
  File "eval_on_synthetic.py", line 46, in main
    save_dir=save_dir)
  File "eval_on_synthetic.py", line 110, in evaluate
    metrics_list=COMPUTE_METRICS)
  File "eval_on_synthetic.py", line 169, in get_metrics
    sample_rate=sample_rate)
  File "/exports/stuart/sagar/asteroid/venv_kevin/lib/python3.6/site-packages/pb_bss/evaluation/wrapper.py", line 87, in __init__
    self.channels = self.observation.shape[-2]
IndexError: tuple index out of range

I have trained the model with some modifications, but unable to evaluate on test_set
The log is mentioned above.

Thank you

**Comment by raikarsagar** [comment]
New commit has resolved the issue. related to pb_bss installation

**Comment by mpariente** [comment]
Thanks for reporting the issue and glad you could solve it.
